### ISSUE TITLE
Cannot launch spacefn-win.exe on Window 7.

### ISSUE THREAD

**Issue by jpec** [lydell/spacefn-win#1]
Hi,
I cannot lauch spacefn-win.exe (last version) on Windows 7 :
![image](https://cloud.githubusercontent.com/assets/421328/4182335/a4543808-372c-11e4-98fa-b5fe2c1aa967.png)
The version of Windows 7 at work :
![image](https://cloud.githubusercontent.com/assets/421328/4182353/fbd5281c-372c-11e4-8a83-c27a8a5a65cc.png)

**Comment by lydell** [comment]
I'm sorry, I have no interest in this project anymore — I haven't even used Windows in a year. I'd suggest you to ask for help at the AutoHotkey forums.
