### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [lydell/spacefn-win#2]
hello @lydell how did you replicate the spacefn layout on linux? Could you share your configuration? thanks

I use ubuntu and raspbian

**Comment by lydell** [comment]
I didn't.

**Comment by g-i-o-r-g-i-o** [comment]
Too bad. It seemed a good idea.

Il lunedì 8 giugno 2015, Simon Lydell notifications@github.com ha scritto:

> I didn't.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lydell/spacefn-win/issues/2#issuecomment-110134604.

## 

Sent from Gmail Mobile

**Comment by severin31** [comment]
You could use
https://github.com/alols/xcape
