### ISSUE TITLE
Git command to download dual is incorrect

### ISSUE THREAD

**Issue by vppencilsharpener** [lydell/spacefn-win#3]
The "git submodule init" command is missing from the main page and "git submodule update" is duplicated. 

Looks like the project maintainer is no longer updating the project, but here is how to use the git repository for this project.

git clone https://github.com/lydell/spacefn-win.git
cd into the spacefn-win directory 
git submodule init
git submodule update

I was able to get this running using AutoHotkey v1.1.22.02 on Windows 7 Pro x64

**Comment by lydell** [comment]
PR?

**Comment by vppencilsharpener** [comment]
PR? ? 

The main project page has these instructions:
_git users might want to run git clone https://github.com/lydell/spacefn-win.git (to download the whole project), followed by git submodule **update** and git submodule **update** (to download dual)._

Which did not work for me. AutoHotKey complained about an unmet dependency on dual (wording or the error may have been different). A little googling and I figured out the git submodule init command was missing.

The instructions then become:
_git users might want to run git clone https://github.com/lydell/spacefn-win.git (to download the whole project), followed by git submodule **init** and git submodule **update** (to download dual)._

Just trying to be helpful. I was not familiar with the git submodule command so I figured I would share the solution.

**Comment by lydell** [comment]
Thanks, that _is_ helpful. I was a bit hurried before. PR means pull request. As you noted, I'm bot really maintaining this anymore, but I'd accept a pull request. For this type of issues it is often easier to send a PR than to open an issue.

**Comment by lydell** [comment]
Fixed by #4.
