### ISSUE TITLE
A more simple AHK solution

### ISSUE THREAD

**Issue by district10** [lydell/spacefn-win#5]
You can map "x" to "y" when holding "space" by `space & x::Send {y}`.

And add `space::space` to make space bar works alone.

**Comment by lydell** [comment]
As mentioned in the readme, I don’t use Autohotkey anymore (and haven’t done so for 3 years). I you feel like creating a simpler AHK solution, go ahead! Let me know when you're done, and I'll add a link to it here!

**Comment by district10** [comment]
I think the idea is great. But the third layout is kind of personal choice, here is an example: <https://github.com/district10/neo_keyboard_layout/blob/master/neo4win/spek.ahk> (QWERTY keyboard plus an extra layout).
